#!/bin/bash


set -e


configfile="./createguest.conf"


ISOIMAGE="/var/lib/libvirt/images/debian-6.0.7-amd64-netinst.iso"
LOCATION="http://ftp.debian.org/debian/dists/squeeze/main/installer-amd64/"
DOMAIN="int.druidenkacke.de"
HOSTNETWORKSETUP="\
interface=eth0 \
netcfg/disable_dhcp=true \
netcfg/get_nameservers=10.17.17.2 \
netcfg/get_ipaddress=10.17.17.249 \
netcfg/get_netmask=255.255.255.0 \
netcfg/get_gateway=10.17.17.2 \
netcfg/confirm_static=true \
"
VCPUS=2
RAM=2048
SIZE=5
PVNAME="vg0"
CONNECT="ziolkowski"
NETWORK="network=intranet"
GRAPHICS="vnc"
PRESEEDNAME="simpleserver"
PRESEEDSOURCEDIR="./preseeds"
PRESEEDTARGET="/var/www/"
PRESEEDSERVER="http://10.17.17.22"

OTHERSETUP="\
mirror/http/proxy=http://10.17.17.22:8080\
"
export http_proxy="http://10.17.17.22:8080"
export https_proxy="http://10.17.17.22:8080"
export ftp_proxy="http://10.17.17.22:8080"

#####
name="$1"
preseedurl="$PRESEEDSERVER/$PRESEEDNAME.cfg"

if [ -f "$configfile" ]; then
    echo "reading $configfile"
    source "$configfile"
fi

if [ -z "$name" ]; then
    echo "need guest name"
    exit 1
fi


# check whether a $name domain already exists
if virsh -c "$CONNECT" domid "$name" 2>/dev/null; then
    echo "there already is a domain called $name. bailing out"
    exit 1
fi

# check whether a $name volume already exists
if virsh -c "$CONNECT" vol-path --pool "$PVNAME" "$name" 2>/dev/null; then
    echo "there already is a volume called $name. bailing out"
    exit 1
fi



echo "copy preseed file to webserver..."
rsync -a "$PRESEEDSOURCEDIR/$PRESEEDNAME.cfg" "$PRESEEDTARGET"


echo "create domain $name..."
virt-install \
    --connect="$CONNECT" \
    --name="$name" \
    --ram="$RAM" \
    --vcpus="$VCPUS" \
    --cpu=host \
    --os-type=linux \
    --virt-type=kvm \
    --noautoconsole \
    --wait=-1 \
    --hvm \
    --network="$NETWORK" \
    --graphics="$GRAPHICS" \
    --disk="/dev/vg0/$name,size=$SIZE" \
    --location="$LOCATION" \
    --extra-args="auto=true hostname=$name domain=$DOMAIN $HOSTNETWORKSETUP $OTHERSETUP url=$preseedurl" 



